global:
  test-registry:
    ingressroutes: # Ingress routes configuration section (optional)
      - name: ""
        apiVersion: traefik.io/v1alpha1
        enabled: true
        serviceName: svc
        entryPoints:
          - web
          - websecure
        routes:
          - match: Host(`test-registry.piwero.com`)
            enabled: true
            kind: Rule
            middlewares: [ ]
            services:
              - kind: Service
                enabled: true
                name: svc
                namespace: ""
                port: 80

test-registry:
  env:
    secret:
      BASIC_AUTH_USER: testuser
      BASIC_AUTH_PASS: ${PASSWORD}

  service:
    servicename: svc
    externalPort: 80


  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 200Mi
    labels: { }
    name: test-registry-storage
    path: /storage
    pv:
      enabled: true
      pvname: test-registry-storage
      capacity:
        storage: 200Mi
      accessMode: ReadWriteOnce
      nfs:
        server: ${IP_NAS}
        path: ${PATH_CM}